// Initial Behaviour
const RANDOMIZE_START_STATE = true
const START_STATE = "01001001000001110011000000"

const LIVES_FROM_REPRODUCTION = 3
const DIES_FROM_UNDERPOPULATION = 1
const DIES_FROM_OVERPOPULATION = 4

// Grid Size
const GRID_SIZE = 10

// style
const CELL_PADDING = 8
const CELL_SIZE = 50
const CELL_RADIUS = 10
const CELL_DEAFULT_COLOR = "#f3fcff"
const CELL_ACTIVE_COLOR = "#ffa600"

// Animation
const FRAME_RATE = 3